### ISSUE TITLE
Fails to build when using the --as-needed linker flag

### ISSUE THREAD

**Issue by dbermond** [oneapi-src/oneVPL-intel-gpu#111]
I'm getting the following build error when using the linker flag `--as-needed`:

```
[100%] Linking CXX shared library ../../__bin/None/libmfx-gen.so
/usr/bin/ld: ../../__lib/None/libvm.a(vm_shared_object_linux32.c.o): in function `vm_so_load':
vm_shared_object_linux32.c:(.text+0xc): undefined reference to `dlopen'
/usr/bin/ld: ../../__lib/None/libvm.a(vm_shared_object_linux32.c.o): in function `vm_so_get_addr':
vm_shared_object_linux32.c:(.text+0x27): undefined reference to `dlsym'
/usr/bin/ld: ../../__lib/None/libvm.a(vm_shared_object_linux32.c.o): in function `vm_so_free':
vm_shared_object_linux32.c:(.text+0x47): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
make[2]: *** [_studio/mfx_lib/CMakeFiles/mfx-gen.dir/build.make:637: __bin/None/libmfx-gen.so.1.2.3] Error 1
make[2]: Leaving directory '/build/onevpl-intel-gpu-git/src/build'
make[1]: *** [CMakeFiles/Makefile2:894: _studio/mfx_lib/CMakeFiles/mfx-gen.dir/all] Error 2
make[1]: Leaving directory '/build/onevpl-intel-gpu-git/src/build'
make: *** [Makefile:136: all] Error 2
make: Leaving directory '/build/onevpl-intel-gpu-git/src/build'
```

How to reproduce:
 - execute `export LDFLAGS='-Wl,--as-needed'` and start to build with cmake.

Removing this flag from `LDFLAGS` makes it to build fine. This flag is enabled by default on Arch Linux build tools.

System information:
  - OS: Arch Linux x86_64
  - compiler: gcc 11.1.0
  - libdrm: 2.4.107
  - libva: 2.12.0

**Comment by dvrogozh** [comment]
@dbermond : can you, please, try fix in #115? it works on my side.

**Comment by dbermond** [comment]
@dvrogozh I can confirm that PR #115 fixes this issue for me.

Thank you for providing the fix.

**Comment by dvrogozh** [comment]
@dbermond : fyi, https://github.com/oneapi-src/oneVPL-intel-gpu/releases/tag/intel-onevpl-21.3.0  includes a fix for --as-needed.

**Comment by dbermond** [comment]
@dvrogozh Thank you. I have updated the Arch Linux packages (currently on the AUR - Arch User Repository).
