### ISSUE TITLE
No "mfx_trace_tal.h" when build oneVPU-intel-gpu

### ISSUE THREAD

**Issue by TerrenceXu** [oneapi-src/oneVPL-intel-gpu#190]
## System information
For all system, just a build issue.

### Describe the current behavior
Build error

### Describe the expected behavior
No build error

## Debug information
build failed in "_studio/shared/mfx_trace/src/mfx_trace.cpp", due to "mfx_trace_tal.h" is not existed but it still try to include.

**Comment by onabiull** [comment]
Fixed with 4b80cea3f0eb71f35cea11ca36409180a63c4790.
