### ISSUE TITLE
Do not install software during build process

### ISSUE THREAD

**Issue by dvrogozh** [oneapi-src/oneVPL-intel-gpu#191]
https://github.com/oneapi-src/oneVPL-intel-gpu/blob/0add4086ee7360166389f5475d93e1064a282002/_studio/mfx_config_trace/CMakeLists.txt#L10

We should NOT install software during build process. All required software are prerequisites and is clear responsibility of end-user. Please, fix ASAP.

**Comment by onabiull** [comment]
Fixed with 8f69dadbf30c91681b53e148a6e11284d1ae373a.
