### ISSUE TITLE
[Question] MFXVideoVPP_Reset MFX_ERR_INCOMPATIBLE_VIDEO_PARAM?

### ISSUE THREAD

**Issue by samuel100u** [oneapi-src/oneVPL-intel-gpu#194]
```
void oneVPLVidEnc::setBackgroundColor()
{
	mfxStatus sts = MFX_ERR_NONE;

	mfxExtVPPComposite &VppCompParams = *(mfxExtVPPComposite *)m_pVppCompParams;
	mfxVPPCompInputStream &inputSteam = *(mfxVPPCompInputStream *)m_pInputStream;
	mfxVideoParam &VppParams = *(mfxVideoParam *)m_pVppParams;

	VppCompParams.Header.BufferId = MFX_EXTBUFF_VPP_COMPOSITE;
	VppCompParams.Header.BufferSz = sizeof(mfxExtVPPComposite);

	VppCompParams.Y = 0x10;
	VppCompParams.U = 0x80;
	VppCompParams.V = 0x80;
	inputSteam.DstX = 0;
	inputSteam.DstY = 0;
	inputSteam.DstH = VppParams.vpp.Out.Height;
	inputSteam.DstW = VppParams.vpp.Out.Width;

	
	VppCompParams.InputStream = &inputSteam;
	VppCompParams.NumInputStream = 1;

	if (m_vVppExtParams.size() == 0)
	{
		m_vVppExtParams.push_back((mfxExtBuffer *)&VppCompParams);
	}

	mfxVideoParam &vppParams = *(mfxVideoParam *)m_pVppParams;

	if (vppParams.ExtParam == NULL)
	{
		vppParams.ExtParam = (mfxExtBuffer **)(m_vVppExtParams.data());

		vppParams.NumExtParam = m_vVppExtParams.size();

		//sts = MFXVideoVPP_Query(m_session, &vppParams, &vppParams);

		sts = MFXVideoVPP_Reset(m_session, &vppParams);
	}
}


```
![image](https://user-images.githubusercontent.com/22620447/147199306-1ede3e1d-09fa-4eed-bcb8-01361793b9af.png)
![image](https://user-images.githubusercontent.com/22620447/147199486-ac629150-b996-4267-9d93-3b743661cbb8.png)

OS : win10
Use libmfx64-gen.dll

**Comment by samuel100u** [comment]
> m_pVppCompParams

This variable already `memset(m_pVppCompParams,0,sizeof(mfxExtVPPComposite ));`

**Comment by samuel100u** [comment]
I think this problem is similar with this [issues](https://github.com/Intel-Media-SDK/MediaSDK/issues/2721)

**Comment by dmitryermilov** [comment]
> I think this problem is similar with this [issues](https://github.com/Intel-Media-SDK/MediaSDK/issues/2721)

It was fixed by https://github.com/oneapi-src/oneVPL-intel-gpu/commit/d24595d8b3145923528c5f0300f8311f28c8647e

**Comment by samuel100u** [comment]
I forgot to inital NumInputStream before MFXVideoVPP_Init. It works now.

**Comment by dmitryermilov** [comment]
> I forgot to inital NumInputStream before MFXVideoVPP_Init. It works now.

Okay. Thanks for letting know!
