### ISSUE TITLE
[regression][Sample_decode] decode.hevc 422 md5 mismatch

### ISSUE THREAD

**Issue by wenqingx** [oneapi-src/oneVPL-intel-gpu#219]
## System information
- CPU information  12th Gen Intel(R) Core(TM) i9-12900
- Platform:TGL ADL
- OS:Ubuntu 20.04.4 LTS
- kernel: 5.15.0-13-generic x86_64
- Good VPL runtime version? ecea384f31a1ffbd239da5b92dbc46ff5b8e59ff
- Bad VPL runtime version? a522459d246b4ba843506eca91edb61743f1a0c4
- Underlying media stack (libva/libgmm/media-driver) version?
- libva : 9e4bdc5c4f7f
- intel-media-driver : e9b57f55f77a
- gmmlib : e1f634c5d5a4
### Describe the current behavior 
In the same 422 192x200 code stream,  the information read by sample does not match.

Reproduce Steps:
 sample_decode h265 -i input.bin

Expected Result:
Input video     HEVC
Output format   YUY2
Input:
  Resolution    192x256
  Crop X,Y,W,H  0,0,192,200
Output:
  Resolution    192x200
Frame rate      60.00
Memory type             vaapi
MediaSDK impl           hw
MediaSDK version        2.7

Actual Result:
Input video     HEVC
Output format   YUY2
Input:
  Resolution    192x256
  Crop X,Y,W,H  0,0,192,144
Output:
  Resolution    192x144
Frame rate      60.00
Memory type             vaapi
MediaSDK impl           hw
MediaSDK version        2.7

**Comment by wenqingx** [comment]
Could you help check this problem ？thanks.

**Comment by Jexu** [comment]
@wenqingx  Please help try above PR, thanks a lot.

**Comment by wenqingx** [comment]
@Jexu This PR fixes the problem.thanks.

**Comment by wangyan-intel** [comment]
Based on the description, this issue comes from Bad VPL runtime version? https://github.com/oneapi-src/oneVPL-intel-gpu/commit/a522459d246b4ba843506eca91edb61743f1a0c4 which is the crop fix from Wayne for MDP-63613. So could you please double check it? It may not be regression and you may need adjust your MD5 golden value.

**Comment by Gvence** [comment]
Yes, https://github.com/oneapi-src/oneVPL-intel-gpu/commit/a522459d246b4ba843506eca91edb61743f1a0c4 for MDP-63613 is a fix and corrected the calculation of crop rectangle. So, it's not a regression, And need to correct the reference YUV.

**Comment by wenqingx** [comment]
Expected Result:Resolution 192x200  ;Actual Result:Resolution 192x144;
The MD5 mismatch is caused by the reduction of the out size.
This PR is the output size restored to 192x200, so the problem of MD5 is fixed.

**Comment by Jexu** [comment]
![image](https://user-images.githubusercontent.com/11835821/178449117-9ced4bfa-0062-4a03-91dc-a775812381d3.png)

The frame size is 192x200, but dispaly content is 192x144. Per above comment, vpl only dumps the content size with https://github.com/oneapi-src/oneVPL-intel-gpu/commit/a522459d246b4ba843506eca91edb61743f1a0c4.

**Comment by wangyan-intel** [comment]
I have just synced with @xhaihao offline. XMPT team will update reference for avoiding this mismatching.

**Comment by mengker33** [comment]
@Jexu I see the input frame size is 192x256，and we only have  conf_win_bottom_offset=56. According to spec: here conformance cropping window contains the luma samples in vertical direction is from 0 to pic_height_in_lima_samples - (SubHeightC * conf_win_bottom_offset + 1). For 422 chroma sampling, SubHeightC is 1, and we should have the display content with height 256 - 1x 56 =200. I don't understand why after https://github.com/oneapi-src/oneVPL-intel-gpu/commit/a522459d246b4ba843506eca91edb61743f1a0c4, the bottom part has been subtracted for twice, which is 144 now. Could you please give a double check? Thanks

**Comment by wangyan-intel** [comment]
@mengker33 Please refer to MDP-63613. Thanks.

**Comment by mengker33** [comment]
> @mengker33 Please refer to MDP-63613. Thanks.

Thanks for the info to resolve my confusion, it is quite clear.
