### ISSUE TITLE
[Regression][TGL][gst-libvpl] decode vc1 cmd hang 

### ISSUE THREAD

**Issue by wenqingx** [oneapi-src/oneVPL-intel-gpu#230]
## System information
- CPU information(`cat /proc/cpuinfo | grep "model name" | uniq`):11th Gen Intel(R) Core(TM) i7-1180G7 @ 1.30GHz
- GPU information(`lspci -nn | grep -E 'VGA|isplay`):00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:9a40] (rev 01)

- Display server if rendering to display (X or wayland):
- Good VPL runtime version? https://github.com/oneapi-src/oneVPL-intel-gpu/commit/e096a304d4cb60878ac34512fee62db6b9b6169d 
- Bad VPL runtime version? https://github.com/oneapi-src/oneVPL-intel-gpu/commit/00152d83a52aca6954d25138836b53991b4c80eb
- Underlying media stack (libva/libgmm/media-driver) version?
- libva : 0a989c9f0af6
- gmmlib : f7194832aa1c
- intel-media-driver : c024d3fa49ef
- onevpl : 2232af4cdb13

## Issue behavior
cmd:gst-launch-1.0 -vf filesrc location=input.vc1 ! 'video/x-wmv,profile=(string)advanced',width=176,height=144,framerate=14/1 ! msdkvc1dec ! videoconvert chroma-mode=none dither=0 ! video/x-raw,format=I420 ! checksumsink2 qos=false file-checksum=false frame-checksum=false plane-checksum=false eos-after=15 dump-output=true dump-location=output.yuv
### Describe the current behavior

**New clock: GstSystemClock
0:00:00.5 / 99:99:99.**

it's hang here,the cmd can't end.

log:
libva info: VA-API version 1.16.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /opt/media/install/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_16
libva info: va_openDriver() returns 0
libva info: VA-API version 1.16.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /opt/media/install/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_16
libva info: va_openDriver() returns 0
Setting pipeline to PAUSED ...
libva info: VA-API version 1.16.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /opt/media/install/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_16
libva info: va_openDriver() returns 0
libva info: VA-API version 1.16.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /opt/media/install/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_16
libva info: va_openDriver() returns 0
Pipeline is PREROLLING ...
Got context from element 'msdkvc1dec0': gst.va.display.handle=context, gst-display=(GstObject)"\(GstVaDisplayDrm\)\ vadisplaydrm1", description=(string)"Intel\ iHD\ driver\ for\ Intel\(R\)\ Gen\ Graphics\ -\ 22.5.3\ \(\)", path=(string)/dev/dri/renderD128;
Got context from element 'msdkvc1dec0': gst.msdk.Context=context, gst.msdk.Context=(GstMsdkContext)"\(GstMsdkContext\)\ msdkcontext1";
/GstPipeline:pipeline0/GstCapsFilter:capsfilter0.GstPad:src: caps = video/x-wmv, profile=(string)advanced, width=(int)176, height=(int)144, framerate=(fraction)14/1, wmvversion=(int)3, format=(string)WVC1, header-format=(string)asf, stream-format=(string)bdu
Redistribute latency...
/GstPipeline:pipeline0/GstMsdkVC1Dec:msdkvc1dec0.GstPad:sink: caps = video/x-wmv, profile=(string)advanced, width=(int)176, height=(int)144, framerate=(fraction)14/1, wmvversion=(int)3, format=(string)WVC1, header-format=(string)asf, stream-format=(string)bdu
/GstPipeline:pipeline0/GstMsdkVC1Dec:msdkvc1dec0.GstPad:src: caps = video/x-raw, format=(string)NV12, width=(int)176, height=(int)144, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)14/1
/GstPipeline:pipeline0/GstVideoConvert:videoconvert0.GstPad:src: caps = video/x-raw, width=(int)176, height=(int)144, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)14/1, format=(string)I420
/GstPipeline:pipeline0/GstCapsFilter:capsfilter1.GstPad:src: caps = video/x-raw, width=(int)176, height=(int)144, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)14/1, format=(string)I420
/GstPipeline:pipeline0/GstCksumImageSink:cksumimagesink0.GstPad:sink: caps = video/x-raw, width=(int)176, height=(int)144, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)14/1, format=(string)I420
/GstPipeline:pipeline0/GstCapsFilter:capsfilter1.GstPad:sink: caps = video/x-raw, width=(int)176, height=(int)144, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)14/1, format=(string)I420
/GstPipeline:pipeline0/GstVideoConvert:videoconvert0.GstPad:sink: caps = video/x-raw, format=(string)NV12, width=(int)176, height=(int)144, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)14/1
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
Redistribute latency...
New clock: GstSystemClock
0:00:00.5 / 99:99:99.

### Describe the expected behavior
cmd runs and outputs the result

**Comment by wenqingx** [comment]
@Sherry-Lin Could you help to check the issue or assign it to someone?
thanks

**Comment by Sherry-Lin** [comment]
@haizhouxu could you take a look?

**Comment by haizhouxu** [comment]
@wenqingx May I know whether this issue is still there in latest version?

This issue should introduced by merge op. And we have a refine(fix) commit behind https://github.com/oneapi-src/oneVPL-intel-gpu/commit/00152d83a52aca6954d25138836b53991b4c80eb

e.g. [Refine for commit](https://github.com/oneapi-src/oneVPL-intel-gpu/commit/c8f558fd117057a041eec187212845c4bd6ffbf2) https://github.com/oneapi-src/oneVPL-intel-gpu/commit/00152d83a52aca6954d25138836b53991b4c80eb

@[gfxVPLsdm](https://github.com/oneapi-src/oneVPL-intel-gpu/commits?author=gfxVPLsdm)
gfxVPLsdm committed 20 days ago

**Comment by wenqingx** [comment]
> @wenqingx May I know whether this issue is still there in latest version?
> 
> This issue should introduced by merge op. And we have a refine(fix) commit behind [00152d8](https://github.com/oneapi-src/oneVPL-intel-gpu/commit/00152d83a52aca6954d25138836b53991b4c80eb)
> 
> e.g. [Refine for commit](https://github.com/oneapi-src/oneVPL-intel-gpu/commit/c8f558fd117057a041eec187212845c4bd6ffbf2) [00152d8](https://github.com/oneapi-src/oneVPL-intel-gpu/commit/00152d83a52aca6954d25138836b53991b4c80eb)
> 
> @[gfxVPLsdm](https://github.com/oneapi-src/oneVPL-intel-gpu/commits?author=gfxVPLsdm) gfxVPLsdm committed 20 days ago

I check it ,the issue still exists.

**Comment by haizhouxu** [comment]
@zhuxuxu-algo 
Could you help check this issue? https://github.com/intel-innersource/drivers.gpu.media.sdk.lib/pull/5618/files also be merged into https://github.com/oneapi-src/oneVPL-intel-gpu/commit/00152d83a52aca6954d25138836b53991b4c80eb(Bad VPL runtime version?)
