### ISSUE TITLE
[DG2/dGPU] VP9dec repeat frame using video2video copy causes corrupt frame

### ISSUE THREAD

**Issue by mengker33** [oneapi-src/oneVPL-intel-gpu#244]
### Describe the current behavior
For vp9 clips (ayuv and p010) with repeat frames, there is video2video copy for the repeat frame, since cm copy is disabled, va copy is applied. The copied frame is corrupted, something looks related to tiled memory as there is **no issue with iGPU.**

Reproduce this issue by: 

- In gstreamer, apply patches from 0020 to 0026 in https://github.com/intel-media-ci/cartwheel-gstreamer/tree/main/patches
- Run gstreamer cmd: <pre><code> gst-launch-1.0 -vf filesrc location=vp9_repeatframe.ivf ! ivfparse ! vp9parse ! msdkvp9dec ! checksumsink2 dump-output=true dump-location=out.yuv </code>
- Frame checksums with repeat frame and the copied one are different.

### Describe the expected behavior
VP9dec can decode repeat frame correctly via video2video copy using va copy. The current va copy follows: vaDeriveImage, then vaPutImage. If I change the va copy method to directly use **vaCopy()** function, it can fix the issue above.

**Comment by mengker33** [comment]
@Jexu, can anyone help on this issue? Thanks

**Comment by mengker33** [comment]
I tried a [PR](https://github.com/intel/media-driver/pull/1569) (for vaGetImage improvement) in media-driver which seems to fix this vp9 copy issue as well. Is this an expected fix or any solution on oneVPL side is being planned?

**Comment by MicroYY** [comment]
Beside the corruption, is decoing vp9 clips also slow, just as decoding h265? A little confused on why corruption is observed, which isn't seen on h265d.

**Comment by mengker33** [comment]
> Beside the corruption, is decoing vp9 clips also slow, just as decoding h265? A little confused on why corruption is observed, which isn't seen on h265d.

Decoding the vp9 clip is not slow, the issue occurred with the video2video copy when decoding vp9 repeated frame which does not exist in hevc codec.  OneVPL runtime applies **vaDeriveImage + vaPutImage** to implement video2video copy and causes the corruption. I am also curious why vaGetImage optimization can fix this vp9 video copy issue.
