### ISSUE TITLE
[Bug]: build error with libva disable X11

### ISSUE THREAD

**Issue by wenqingx** [oneapi-src/oneVPL-intel-gpu#247]
libva:https://github.com/intel/libva/commit/da4a18fe814c9695f420d466ad3065cebdbe288a
vpl-runtime:https://github.com/oneapi-src/oneVPL-intel-gpu/commit/7525419a94387b5e462ba2c55e2157c69f64e037

If libva does not enable X11 when compiling the vpl-runtime, you will encounter a build error.
The configuration I just pulled is the latest one, which I reproduced on TGL.
But it seems that this has nothing to do with the platform

If I add "-- enable - x11" when config and build libva, this issue will be fixed.

except:vpl-runtime can build without X11.

**Comment by Jexu** [comment]
Refer to fix in media driver: https://github.com/intel/media-driver/issues/1524

**Comment by nyanmisaka** [comment]
> Need same fix in vlp by refering to the fix in media driver: [intel/media-driver#1524](https://github.com/intel/media-driver/issues/1524)

I cannot reproduce this issue in vpl. See this commit: 64977c4baf3e04059c0657d5f9bdd60fd385c2ad

> Removed support of ENABLE_DRM and ENABLE_X11 options.
If x11 packages are not found samples will be built without x11
support. Packages libva and libdrm are processed as mandatory to
build libraries and samples

**Comment by wenqingx** [comment]
> 
Sorry, I wasn't alerted to this reply.
is it a fixed patch? if yes i will verify it。

**Comment by wenqingx** [comment]
> > Need same fix in vlp by refering to the fix in media driver: [intel/media-driver#1524](https://github.com/intel/media-driver/issues/1524)
> 
> I cannot reproduce this issue in vpl. See this commit: [64977c4](https://github.com/oneapi-src/oneVPL-intel-gpu/commit/64977c4baf3e04059c0657d5f9bdd60fd385c2ad)
> 
> > Removed support of ENABLE_DRM and ENABLE_X11 options.
> > If x11 packages are not found samples will be built without x11
> > support. Packages libva and libdrm are processed as mandatory to
> > build libraries and samples

Sorry, I wasn't alerted to this reply.
is it a fixed patch? if yes i will verify it。

**Comment by wenqingx** [comment]
I tried to compile when libva did not add -- enable x11. There was no issue in the reproduction. I thought it was fixed. Thank you.
