### ISSUE TITLE
Incoherent Caps on MFX_EXTBUFF_VPP_FIELD_WEAVING

### ISSUE THREAD

**Issue by gchapdel** [oneapi-src/oneVPL-intel-gpu#249]
## System information
- CPU information(`cat /proc/cpuinfo | grep "model name" | uniq`):
model name      : 12th Gen Intel(R) Core(TM) i5-1235U
- GPU information(`lspci -nn | grep -E 'VGA|isplay`):
00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:46a8] (rev 0c)
- Display server if rendering to display(X or wayland):
X

### Describe the current behaviour

The format caps returned from _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp VideoVPPHW::CheckFormatLimitation() do not reflect the format that can be set for the operation MFX_EXTBUFF_VPP_FIELD_WEAVING. CheckFormat specify many formats (NV12, P010, P016, YUY2, Y210, Y216, Y410, Y416 and AYUV) when in fact on execution only NV12 seems to work. In _studio/mfx_lib/vpp/src/mfx_vvp_hw.cpp ValidateParams() there is a check if MFX_EXTBUFF_VPP_FIELD_WEAVING is implied it does not allow other operations but the ExtBuffer MFX_EXTBUFF_VPP_CSC is implied if other formats than NV12, NV16 or P010 are set.

### Describe the expected behaviour

I would like to know clearly which pixel format is supported for an operation since the caps, the documentation and the code do not give the same information.

## Debug information
- What's libva/libva-utils/gmmlib/media-driver/VPL runtime version?
2.14.0/2.14.0/intel-gmmlib-22.1.2/22.3.1/intel-onevpl-22.3.2
- Could you confirm whether GPU hardware exist or not by `ls /dev/dri`?
card0  renderD128
- Could you attach dmesg log if it's GPU hang by `dmesg >dmesg.log 2>&1`?

- Could you provide vainfo log if possible by `vainfo -a >vainfo.log 2>&1`?
- Could you provide strace log if possible by `strace YOUR_CMD >strace.log 2>&1`?
- Could you provide libva trace log if possible? Run cmd `export LIBVA_TRACE=/tmp/libva_trace.log` first then execute the case.
- Do you want to contribute a PR? (yes/no):
no
[vainfo.log](https://github.com/oneapi-src/oneVPL-intel-gpu/files/9954243/vainfo.log)
[dmesg.log](https://github.com/oneapi-src/oneVPL-intel-gpu/files/9954244/dmesg.log)

**Comment by intel-mediadev** [comment]
Auto Created VSMGWL-63157 for further analysis.

**Comment by MicroYY** [comment]
Fixed by: https://github.com/oneapi-src/oneVPL-intel-gpu/commit/205bdb828b70439482d96dc398727b975523866c
