### ISSUE TITLE
VP8 decoding doesn't work with MFX_IMPL_VIA_D3D11

### ISSUE THREAD

**Issue by nyanmisaka** [oneapi-src/oneVPL-intel-gpu#254]
## System information
- GPU information: UHD 630 / Gen9 / KBLx

## Issue behavior

VP8 decoding doesn't work with `MFX_IMPL_VIA_D3D11` impl.

### Describe the current behavior
Current [ffmpeg mainline](https://github.com/FFmpeg/FFmpeg/blob/d7a5f068c237e61e5a1a45f64a7fb1224401986f/libavutil/hwcontext_qsv.c#L2125) has default the MFX impl to D3D11 on Windows, which makes VP8 decoding fail due to some hardcoded lines in the MSDK/VPL runtime:
https://github.com/oneapi-src/oneVPL-intel-gpu/blob/8b2f8edc4190efa45742eaec1e2b16b41f1fe690/_studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_hw.cpp#L139-L142

I noticed this line was committed 6 years ago, is it still correct?

### Describe the expected behavior

VP8 decoding should work with `MFX_IMPL_VIA_D3D11` impl.

**Comment by nyanmisaka** [comment]
> @nyanmisaka
> Thanks for your reporting. So far VPL only supports TGL+ platform which doesn't support VP8 decoder. Could you please use legacy MSDK API to decode VP8 clip on UHD 630 / Gen9 / KBLx?
> The following can be the reference:
> https://github.com/oneapi-src/oneVPL/blob/master/README.md

Yes it works on UHD 630 but you must specify MFX impl to D3D9 if the ffmpeg is compiled with onevpl.

**Comment by wangyan-intel** [comment]
> > @nyanmisaka
> > Thanks for your reporting. So far VPL only supports TGL+ platform which doesn't support VP8 decoder. Could you please use legacy MSDK API to decode VP8 clip on UHD 630 / Gen9 / KBLx?
> > The following can be the reference:
> > https://github.com/oneapi-src/oneVPL/blob/master/README.md
> 
> Yes it works on UHD 630 but you must specify MFX impl to D3D9 if the ffmpeg is compiled with onevpl.

Officially VPL doesn't support UHD630. 
@xhaihao Could you please provide the comments?

**Comment by nyanmisaka** [comment]
> Officially VPL doesn't support UHD630.

You're right. But VPL loader will automatically select MSDK or VPL according to the platform.

ffmpeg(vpl) -> load msdk on legacy platform.

**Comment by wangyan-intel** [comment]
> > Officially VPL doesn't support UHD630.
> 
> You're right. But VPL loader will automatically select MSDK or VPL according to the platform.
> 
> ffmpeg(vpl) -> load msdk on legacy platform.

Yes. We will check MSDK on legacy platform at first. It should support VP8 decode based on D3D11.

**Comment by nyanmisaka** [comment]
@wangyan-intel 

https://github.com/Intel-Media-SDK/MediaSDK/blob/73c6ca577f83b1c451e28517e6bd41045c2f9097/_studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_hw.cpp#L133

As you can see the D3D11 is not available for VP8 in legacy MSDK, so it fails the ffmpeg by default.

**Comment by wangyan-intel** [comment]
> @wangyan-intel
> 
> https://github.com/Intel-Media-SDK/MediaSDK/blob/73c6ca577f83b1c451e28517e6bd41045c2f9097/_studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_hw.cpp#L133
> 
> As you can see the D3D11 is not available for VP8 in legacy MSDK, so it fails the ffmpeg by default.

Sure. We are checking it.

**Comment by huangli2018** [comment]
MSDK wants to get VP8 coefficient probabilities buffer from D3D11 call ID3D11VideoContext：：GetDecoderBuffer(), but D3D11_VIDEO_DECODER_BUFFER_TYPE（https://learn.microsoft.com/zh-cn/windows/win32/api/d3d11/ne-d3d11-d3d11_video_decoder_buffer_type） didn't defined
coefficient probabilities buffer. So legacy MSDK does not support VP8 in D3D11

**Comment by nyanmisaka** [comment]
> MSDK wants to get VP8 coefficient probabilities buffer from D3D11 call ID3D11VideoContext：：GetDecoderBuffer(), but D3D11_VIDEO_DECODER_BUFFER_TYPE（[https://learn.microsoft.com/zh-cn/windows/win32/api/d3d11/ne-d3d11-d3d11_video_decoder_buffer_type）](https://learn.microsoft.com/zh-cn/windows/win32/api/d3d11/ne-d3d11-d3d11_video_decoder_buffer_type%EF%BC%89) didn't defined coefficient probabilities buffer. So legacy MSDK does not support VP8 in D3D11

That make sense to it. Close this for now.
