### ISSUE TITLE
The build is not reproducible (due to CMAKE_SYSTEM_VERSION)

### ISSUE THREAD

**Issue by tjaalton** [oneapi-src/oneVPL-intel-gpu#255]
Hi, I got this bug report on Debian:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006455

which means that the build_info of the library binary has the build env kernel information on it, which makes the build unreproducible. Would that be possible to drop from BUILD_INFO?

**Comment by tjaalton** [comment]
anyone?

**Comment by Sherry-Lin** [comment]
@yefeizhou could you take a look?
