### ISSUE TITLE
External BRC not working on ADL-P platform

### ISSUE THREAD

**Issue by joojler** [oneapi-src/oneVPL-intel-gpu#263]
## System information
- CPU information(`cat /proc/cpuinfo | grep "model name" | uniq`):
model name      : 12th Gen Intel(R) Core(TM) i7-1265UE

- GPU information(`lspci -nn | grep -E 'VGA|isplay`):
00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:4628] (rev 0c)

- Display server if rendering to display(X or wayland):
Doesn't matter

### Describe the current behavior
on ADL-P platform
./sample_multi_transcode -i::h264 /home/intel/1080p.h264 -o::h264 james.avc -extbrc::on reported MFX_ERR_DEVICE_FAIL
./sample_multi_transcode -i::h264 /home/intel/1080p.h264 -o::h264 james.avc -extbrc::off can work properly

on TGL-U platform, both of all work properly. Did some debug, it's due to the onevpl ext asc doesn't support ADL-P platform. 
the code is as below in _studio/shared/asc/asc.cpp. Not sure why we didn't add ADL-P support, please help to confirm. 

ASC::InitGPUsurfmfxStatus ASC::InitGPUsurf(CmDevice* pCmDevice) {
#ifdef MFX_ENABLE_KERNELS
    INT res = CM_SUCCESS;
    m_subSamplingEv = nullptr;
    m_frameCopyEv   = nullptr;

    Reset_ASCCmDevice();
    m_device = pCmDevice;
    if (!m_device)
        res = CM_FAILURE;

    SCD_CHECK_CM_ERR(res, MFX_ERR_DEVICE_FAILED);
    Set_ASCCmDevice();

    mfxU32 hwType = 0;
    size_t hwSize = sizeof(hwType);
    res = m_device->GetCaps(CAP_GPU_PLATFORM, hwSize, &hwType);
    SCD_CHECK_CM_ERR(res, MFX_ERR_DEVICE_FAILED);

    res = m_device->CreateQueue(m_queue);
    SCD_CHECK_CM_ERR(res, MFX_ERR_DEVICE_FAILED);

    switch (hwType)
    {
    case PLATFORM_INTEL_BDW:
    case PLATFORM_INTEL_SKL:
    case PLATFORM_INTEL_KBL:
    case PLATFORM_INTEL_GLK:
    case PLATFORM_INTEL_CFL:
    case PLATFORM_INTEL_CNL:
    case PLATFORM_INTEL_BXT:
    case PLATFORM_INTEL_ICL:
    case PLATFORM_INTEL_ICLLP:
        return MFX_ERR_UNSUPPORTED;
    **case PLATFORM_INTEL_ADL_S:
    case PLATFORM_INTEL_TGLLP:
    case PLATFORM_INTEL_RKL:
    case PLATFORM_INTEL_DG1:
    case PLATFORM_INTEL_ADL_N:**

        res = m_device->LoadProgram((void *)genx_scd_gen12lp, sizeof(genx_scd_gen12lp), m_program, "nojitter");
        break;
    default:
        res = CM_NOT_IMPLEMENTED;
    }
    SCD_CHECK_CM_ERR(res, MFX_ERR_DEVICE_FAILED);

### Describe the expected behavior
./sample_multi_transcode -i::h264 /home/intel/1080p.h264 -o::h264 james.avc -extbrc::on can work properly

## Debug information
- What's libva/libva-utils/gmmlib/media-driver/VPL runtime version?
- Could you confirm whether GPU hardware exist or not by `ls /dev/dri`?
- Could you attach dmesg log if it's GPU hang by `dmesg >dmesg.log 2>&1`?
- Could you provide vainfo log if possible by `vainfo -a >vainfo.log 2>&1`?
- Could you provide strace log if possible by `strace YOUR_CMD >strace.log 2>&1`?
- Could you provide libva trace log if possible? Run cmd `export LIBVA_TRACE=/tmp/libva_trace.log` first then execute the case.
All of above log doesn't matter.

- Do you want to contribute a PR? (yes/no):
yes

**Comment by DenWolf** [comment]
Hi @joojler ,

I see that ADL_P support was added by the next patch - https://github.com/oneapi-src/oneVPL-intel-gpu/commit/6f0ca080dcc7eeb773a89b1faeb59a4cb6418524

I suppose that current issue should be already - could you please help to clarify it and Close the actual ticket if everything is OK?

Thank you,
Denis

**Comment by OttoYang** [comment]
@joojler Hi James, does the patch work for you ?

**Comment by intel-mediadev** [comment]
Auto Created VSMGWL-66142 for further analysis.

**Comment by OttoYang** [comment]
@joojler  Hi James, I'll close this issue as the fix has been committed and verified.  
Feel free to reopen it if it doesn't work for you. Thanks.
