### ISSUE TITLE
[Regression]ffmpeg-libvpl encode av1 test fail by "Aborted (core dumped)"

### ISSUE THREAD

**Issue by wenqingx** [oneapi-src/oneVPL-intel-gpu#267]
## System information
- CPU information(`cat /proc/cpuinfo | grep "model name" | uniq`):12th Gen Intel(R) Core(TM) i7-12700
- GPU information(`lspci -nn | grep -E 'VGA|isplay`):Intel Corporation Device [8086:56a5] (rev 05)
- Display server if rendering to display (X or wayland):
- Good VPL runtime version? https://github.com/oneapi-src/oneVPL-intel-gpu/commit/13d3f7c6dcb77e8419bc7d650e852de994db34b3 
- Bad VPL runtime version?  https://github.com/oneapi-src/oneVPL-intel-gpu/commit/c80fab6cdd888ee12319f31b551141d571556861
- Underlying media stack (libva/libgmm/media-driver) version?
- libva:9ac72efe2e123321d8fd5500fb1aca51cd31bc97
- gmmlib:3c41a692b68df52382f0e9ba5ce5e955ed67908f
- media-dirver:08173bd0d58ea2a9d58a12d6b4816d011c27212a

### Describe the current behavior

all encode av1 test cases  fail by "Aborted (core dumped)" in ffmpeg-libvpl on DG2

cmd:
ffmpeg -v verbose -hwaccel qsv -init_hw_device qsv=qsv,child_device=/dev/dri/renderD128 -hwaccel_output_format qsv -f rawvideo -pix_fmt yuv420p -s:v 720x480  -r:v 30 -i input.yuv -vf 'format=nv12,hwupload=extra_hw_frames=120' -an -c:v av1_qsv  -profile:v main -preset 4 -g 30 -bf 2 -b:v 2000k -maxrate 2000k -tile_cols 2 -tile_rows 2 -low_power 1 -vframes 150 -y output.ivf

log:
[AVHWDeviceContext @ 0x559fddbafd00] libva: VA-API version 1.17.0
[AVHWDeviceContext @ 0x559fddbafd00] libva: User requested driver 'iHD'
[AVHWDeviceContext @ 0x559fddbafd00] libva: Trying to open /home/media-ci/media-env/media/build/lib/dri/iHD_drv_video.so
[AVHWDeviceContext @ 0x559fddbafd00] libva: Found init function __vaDriverInit_1_17
[AVHWDeviceContext @ 0x559fddbafd00] libva: va_openDriver() returns 0
[AVHWDeviceContext @ 0x559fddbafd00] Initialised VAAPI connection: version 1.17
[AVHWDeviceContext @ 0x559fddbafd00] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 23.1.1 (08173bd0d).
[AVHWDeviceContext @ 0x559fddbafd00] Driver not found in known nonstandard list, using standard behaviour.
[AVHWDeviceContext @ 0x559fddbaf740] Use Intel(R) oneVPL to create MFX session, API version is 2.8, the required implementation version is 1.3
libva info: VA-API version 1.17.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /home/media-ci/media-env/media/build/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva info: va_openDriver() returns 0
libva info: VA-API version 1.17.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /home/media-ci/media-env/media/build/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva info: va_openDriver() returns 0
[AVHWDeviceContext @ 0x559fddbaf740] Initialize MFX session: implementation version is 2.8
[rawvideo @ 0x559fdde94f80] Estimating duration from bitrate, this may be inaccurate
Input #0, rawvideo, from '/opt/media/ci/assets/otc-media/sanity/yuv/720x480p.yuv':
  Duration: 00:00:42.93, start: 0.000000, bitrate: 124416 kb/s
  Stream #0:0: Video: rawvideo, 1 reference frame (I420 / 0x30323449), yuv420p, 720x480, 124416 kb/s, 30 tbr, 30 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> av1 (av1_qsv))
Press [q] to stop, [?] for help
[graph 0 input from stream 0:0 @ 0x559fdddef600] w:720 h:480 pixfmt:yuv420p tb:1/30 fr:30/1 sar:0/1
[auto_scale_0 @ 0x559fddccce40] w:iw h:ih flags:'' interl:0
[Parsed_format_0 @ 0x559fddea2480] auto-inserting filter 'auto_scale_0' between the filter 'graph 0 input from stream 0:0' and the filter 'Parsed_format_0'
[auto_scale_0 @ 0x559fddccce40] w:720 h:480 fmt:yuv420p sar:0/1 -> w:720 h:480 fmt:nv12 sar:0/1 flags:0x00000004
[AVHWDeviceContext @ 0x559fddf08e00] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 23.1.1 (08173bd0d).
[AVHWDeviceContext @ 0x559fddf08e00] Driver not found in known nonstandard list, using standard behaviour.
[AVHWFramesContext @ 0x559fddcc86c0] Use Intel(R) oneVPL to create MFX session, API version is 2.8, the required implementation version is 2.8
[AVHWFramesContext @ 0x559fddcc86c0] Initialize MFX session: implementation version is 2.8
[av1_qsv @ 0x559fddda4980] Using input frames context (format qsv) with av1_qsv encoder.
[av1_qsv @ 0x559fddda4980] Encoder: input is video memory surface
[av1_qsv @ 0x559fddda4980] Use Intel(R) oneVPL to create MFX session with the specified MFX loader
[av1_qsv @ 0x559fddda4980] Using the constant bitrate (CBR) ratecontrol method
[av1_qsv @ 0x559fddda4980] profile: av1 main; level: 30
[av1_qsv @ 0x559fddda4980] GopPicSize: 30; GopRefDist: 3; GopOptFlag:; IdrInterval: 0
[av1_qsv @ 0x559fddda4980] TargetUsage: 4; RateControlMethod: CBR
[av1_qsv @ 0x559fddda4980] BufferSizeInKB: 1000; InitialDelayInKB: 250; TargetKbps: 2000; MaxKbps: 2000; BRCParamMultiplier: 1
[av1_qsv @ 0x559fddda4980] NumRefFrame: 2
[av1_qsv @ 0x559fddda4980] IntRefType: 0; IntRefCycleSize: 0; IntRefQPDelta: 0; IntRefCycleDist: 0
[av1_qsv @ 0x559fddda4980] MaxFrameSize: 0;
[av1_qsv @ 0x559fddda4980] BitrateLimit: unknown; MBBRC: OFF; ExtBRC: unknown
[av1_qsv @ 0x559fddda4980] VDENC: ON
[av1_qsv @ 0x559fddda4980] BRefType: off
[av1_qsv @ 0x559fddda4980] PRefType: default
[av1_qsv @ 0x559fddda4980] MinQPI: 0; MaxQPI: 0; MinQPP: 0; MaxQPP: 0; MinQPB: 0; MaxQPB: 0
[av1_qsv @ 0x559fddda4980] FrameRateExtD: 1; FrameRateExtN: 30
[av1_qsv @ 0x559fddda4980] NumTileRows: 2; NumTileColumns: 2; NumTileGroups: 1
[av1_qsv @ 0x559fddda4980] WriteIVFHeaders: OFF
[av1_qsv @ 0x559fddda4980] LowDelayBRC: OFF
[av1_qsv @ 0x559fddda4980] MaxFrameSize: 0;
Automatically inserted bitstream filter 'av1_metadata'; args='td=insert'
Output #0, ivf, 
  Metadata:
    encoder         : Lavf59.38.100
  Stream #0:0: Video: av1, 1 reference frame (AV01 / 0x31305641), qsv(tv, progressive), 720x480 (0x0), q=2-31, 2000 kb/s, 30 fps, 30 tbn
    Metadata:
      encoder         : Lavc59.63.100 av1_qsv
free(): invalid pointer.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A
**Aborted (core dumped)**

### Describe the expected behavior
pass

**Comment by wenqingx** [comment]
I just found that this commit has been reversed.
https://github.com/oneapi-src/oneVPL-intel-gpu/commit/e1f73f8a39d62ba01a6fa7a59140e7986e9bb3fc

**Comment by Jexu** [comment]
So could we close this issue now since it has been reverted.

**Comment by wenqingx** [comment]
> So could we close this issue now since it has been reverted.

sure,because I'm not sure whether the reason for the commit [reverse](https://github.com/oneapi-src/oneVPL-intel-gpu/commit/e1f73f8a39d62ba01a6fa7a59140e7986e9bb3fc) is the same as the issue. closed thanks
