### ISSUE TITLE
sample_encode produce different bitstream for external and internal allocators

### ISSUE THREAD

**Issue by Fantast34** [oneapi-src/oneVPL-intel-gpu#27]
sample_encode h265 -i input_1920x1080.nv12 -o output.hevc -w 1920 -h 1080 -nv12 -api2x_dispatcher
and
sample_encode h265 -i input_1920x1080.nv12 -o output.hevc -w 1920 -h 1080 -nv12 -api2x_dispatcher -api2x_internalmem
produce different streams. Is it expected behavior?

**Comment by dvrogozh** [comment]
@mgonchar, @dgurulev : can you take a look?

**Comment by mgonchar** [comment]
@dvrogozh I believe it most probably related to https://github.com/oneapi-src/oneVPL/issues/18

We have tests on RT side where we compare legacy (ext allocator) vs VPL (internal allocation) approach, for AVC we always see b2b result

**Comment by mgonchar** [comment]
@Fantast34 answering your question, in general it is not expected, output between two memory models should be b2b

**Comment by Fantast34** [comment]
@mgonchar  I can confirm that fix #17 is working for us, except cases of flashing please see my comments there.
