### ISSUE TITLE
[Regression][ffmpeg-qsv][DG2]Many cases fail by "4bb7c228"

### ISSUE THREAD

**Issue by wenqingx** [oneapi-src/oneVPL-intel-gpu#270]
## System information
- CPU information(`cat /proc/cpuinfo | grep "model name" | uniq`):
- GPU information(`lspci -nn | grep -E 'VGA|isplay`):
- Display server if rendering to display (X or wayland):
- Good VPL runtime version?
- Bad VPL runtime version?
- Underlying media stack (libva/libgmm/media-driver) version?
libva:97cbc87c9435
gmmlib:3c41a692b68d
media-driver:929866c80d13
### Describe the current behavior

We have caught a large number of failure cases in BAT, including part of encode and almost all Vpp on DG2.

such as :
`ffmpeg -hwaccel qsv -init_hw_device qsv=qsv,child_device=/dev/dri/renderD128 -hwaccel_output_format qsv -v verbose -f rawvideo -pix_fmt nv12 -s:v 1280x720 -i input.yuv -vf 'format=nv12|qsv,hwupload=extra_hw_frames=16,vpp_qsv=detail=0,hwdownload,format=nv12' -pix_fmt nv12 -f rawvideo -fps_mode passthrough -an -vframes 10 -y output.yuv
`
log:
graph 0 input from stream 0:0 @ 0x556dc2ff0100] w:1280 h:720 pixfmt:nv12 tb:1/25 fr:25/1 sar:0/1
[AVHWDeviceContext @ 0x556dc2ff03c0] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 23.1.3 ().
[AVHWDeviceContext @ 0x556dc2ff03c0] Driver not found in known nonstandard list, using standard behaviour.
[Parsed_vpp_qsv_2 @ 0x556dc2fedf40] qsv vpp pass through mode.
[AVHWFramesContext @ 0x556dc2ff55c0] Use Intel(R) Media SDK to create MFX session, API version is 1.35, the required implementation version is 1.255
[AVHWFramesContext @ 0x556dc2ff55c0] Initialize MFX session: implementation version is 1.255
[AVHWFramesContext @ 0x556dc2ff55c0] Use Intel(R) Media SDK to create MFX session, API version is 1.35, the required implementation version is 1.255
[AVHWFramesContext @ 0x556dc2ff55c0] Initialize MFX session: implementation version is 1.255
**Segmentation fault (core dumped)**

**Comment by uartie** [comment]
FBC link: 4bb7c228af570a5d29dbea4604eddcea4ee2339e

**Comment by Jexu** [comment]
@fenhu could you take a look for this issue?

**Comment by fenhu** [comment]
I am look for it. Need test env. you just provie the test cmd, not have install steps . I still don't know how to reproduce it.

**Comment by intel-mediadev** [comment]
Auto Created VSMGWL-63155 for further analysis.

**Comment by fenhu** [comment]
sorry. I am already fix it. and PR merge to opensource. How to close it?

**Comment by fenhu** [comment]
fixed PR: https://github.com/intel-innersource/drivers.gpu.media.sdk.lib/pull/6788
which was merged [VPL] master-1.0.3714

**Comment by fenhu** [comment]
Opensource Link: https://github.com/oneapi-src/oneVPL-intel-gpu/commit/c32d57a8412a279d23b6502eca32a6bfb36c118f

would you help to verify and close it?

Thanks
Molly
