### ISSUE TITLE
Error when run sample_multi_transcode(onevpl) with my enctools.so

### ISSUE THREAD

**Issue by changliwu** [oneapi-src/oneVPL-intel-gpu#277]
Hi,
     I want to test lpla funtcion by enctools,  First, I test it ok with https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-jammy-arc.html.
      And then, I download source codes from https://github.com/oneapi-src/oneVPL-intel-gpu, build it to generator the entools.so and use my enctools.so to replace, it go wrong.
      I find the size of my enctools.so is smaller than ok.
test@test:/usr/lib/x86_64-linux-gnu/libmfx-gen$ ls -al
total 3492
drwxr-xr-x  2 root root    4096  4月  1 11:20 .
drwxr-xr-x 99 root root   77824  4月  1 11:25 ..
-rw-r--r--  1 root root  154384  4月  1 11:25 enctools.so_my
-rw-r--r--  1 root root 3332424  1月 18 12:09 enctools.so_ok

     The test run like this:
test@test$ ./sample_multi_transcode -i::nv12 /media/test/88C6D3C9C6D3B622/src_nv12.yuv -hw -async 5 -device /dev/dri/renderD128   -u fast -b 2000 -vbr -n 3000 -w 1920 -h 1080 -override_encoder_framerate 25 -lowpower:on -lad 50  -extbrc::on -AdaptiveI:on -AdaptiveB:on -dist 8 -num_ref 4 -gop_size 256   -NalHrdConformance:off -VuiNalHrdParameters:off -hrd 500   -InitialDelayInKB 500 -MaxKbps 4000 -o::h265 src_nv12.h265
Multi Transcoding Sample Version 8.4.27.0

warning: system memory will be used
CONFIGURE LOADER: required implementation: hw 
CONFIGURE LOADER: required implementation mfxAccelerationMode: MFX_ACCEL_MODE_VIA_VAAPI 
libva info: VA-API version 1.17.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva info: va_openDriver() returns 0
libva info: VA-API version 1.17.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva info: va_openDriver() returns 0
libva info: VA-API version 1.17.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva info: va_openDriver() returns 0
Session 0:
[WARNING] Configuration changed on the Query() call
mfx.TargetUsage:5 changed to mfx.TargetUsage:4 
mfx.DecodedOrder:5 changed to mfx.DecodedOrder:4 
mfx.JPEGChromaFormat:5 changed to mfx.JPEGChromaFormat:4 
mfx.Interleaved:5 changed to mfx.Interleaved:4 
ext.CDO2.BitrateLimit:32 changed to ext.CDO2.BitrateLimit:0 
Pipeline surfaces number (EncPool): 63
Pipeline surfaces number (DecPool): 2

[ERROR], sts=MFX_ERR_INVALID_VIDEO_PARAM(-15), Init, m_pmfxENC->Init failed at /home/test/onevpl/20230329_onevpl/oneVPL-2023.1.3/tools/legacy/sample_multi_transcode/src/pipeline_transcode.cpp:4322

[ERROR], sts=MFX_ERR_INVALID_VIDEO_PARAM(-15), Init, pThreadPipeline->pPipeline->Init failed at /home/test/onevpl/20230329_onevpl/oneVPL-2023.1.3/tools/legacy/sample_multi_transcode/src/sample_multi_transcode.cpp:645

[ERROR], sts=MFX_ERR_INVALID_VIDEO_PARAM(-15), main, transcode.Init failed at /home/test/onevpl/20230329_onevpl/oneVPL-2023.1.3/tools/legacy/sample_multi_transcode/src/sample_multi_transcode.cpp:1649

## System information
CPU:
test@test$ sudo cat /proc/cpuinfo | grep "model name"| uniq
model name	: 12th Gen Intel(R) Core(TM) i3-12100F

GPU(Mesa Intel(R) Arc(tm) A380 Graphics (DG2)):
test@test$ sudo lspci -nn | grep -E 'VGA|isplay'
03:00.0 VGA compatible controller [0300]: Intel Corporation Device [8086:56a5] (rev 05)

test@test$ ls /dev/dri
by-path  card0  renderD128
[dmesg.log](https://github.com/oneapi-src/oneVPL-intel-gpu/files/11128406/dmesg.log)
[log.zip](https://github.com/oneapi-src/oneVPL-intel-gpu/files/11128407/log.zip)

**Comment by dvrogozh** [comment]
To build enctools with all the features you need to configure with additional non-default option `-DMFX_ENABLE_AENC=ON`:
https://github.com/oneapi-src/oneVPL-intel-gpu/blob/d9ab3e58d9ef06be421646dfc17aab52f856a28a/builder/BuildOptions.cmake#L117
like is being done in media-delivery project:
https://github.com/intel/media-delivery/blob/ab68f633c71f0c1de6b3e93368e1de361cd5caa0/docker/ubuntu20.04/selfbuild-prodkmd/Dockerfile#L204

Mind that above option enables linkage against pre-built binary library (called libaenc) located here: https://github.com/oneapi-src/oneVPL-intel-gpu/blob/main/contrib/aenc/libaenc.a. Library is excluded from default build since some Linux distros such as Debian and Fedora don't allow binary to package software.

**Comment by nyanmisaka** [comment]
> To build enctools with all the features you need to configure with additional non-default option `-DMFX_ENABLE_AENC=ON`

So it'd better if intel can mention this hidden option in the [Build steps](https://github.com/oneapi-src/oneVPL-intel-gpu#build-steps).

**Comment by changliwu** [comment]
I use  cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/opt/intel/samples \
    -DCMAKE_INSTALL_LIBDIR=/opt/intel/samples/lib \
    -DMFX_ENABLE_AENC=ON \
    .. 
to build,it run ok, thanks very much!
