### ISSUE TITLE
[Regression]: HEVC 10bit decode failed

### ISSUE THREAD

**Issue by mamingy2** [oneapi-src/oneVPL-intel-gpu#281]
### Which component impacted?

Decode

### Is it regression? Good in old configuration?

Yes, it's good in old version

#### 1. Environment
HEVC 422 decoding with mistakes.
Linux. TGL. Other stacks are up-to-date.

-good version:
e36fe4101a1d9a1369e638347a77276ad8bc3372
-bad version:
764e65926a13b46f152e24d57a11562b270129da
#### 2. Cmdline:
```
./sample_decode h265 -hw -i input.bin -o output.yuv
```
```
ffmpeg -v verbose -hwaccel qsv -init_hw_device qsv=qsv,child_device=/dev/dri/renderD128 -hwaccel_output_format yuyv422 -hwaccel_flags allow_profile_mismatch -c:v hevc_qsv -i input.bin -lavfi 'null' -c:v rawvideo -pix_fmt yuv422p -fps_mode passthrough -autoscale 0 -y -f tee 'output.yuv|[f=md5]pipe:1'
```
#### 3. Results 
Before 764e65926a13b46f152e24d57a11562b270129da:
![422](https://user-images.githubusercontent.com/109509648/233244986-f1ed1b69-53cb-4381-be37-da2fd4a05698.png)
After:
![422_false](https://user-images.githubusercontent.com/109509648/233244948-4167c461-0cef-4923-8bf8-4b97f73aa980.png)

### What's the usage scenario when you are seeing the problem?

Others

### Do you want to contribute a patch to fix the issue?

No.

**Comment by intel-mediadev** [comment]
Auto Created VSMGWL-64414 for further analysis.

**Comment by mamingy2** [comment]
Sry, my mistake.
