### ISSUE TITLE
[Bug]: I7-12700 vpl encoder change resolution problem

### ISSUE THREAD

**Issue by DaveHu-TVU** [oneapi-src/oneVPL-intel-gpu#282]
### Which component impacted?

Encode

### Is it regression? Good in old configuration?

None

### What happened?

https://github.com/oneapi-src/oneVPL-intel-gpu/releases/tag/intel-onevpl-23.1.5
vbr
1:init()
2: Encode 100 frames of 1920x1080 video, then modify the resolution to 960x540 or 640x480 Reset function will report error: MFX_ERR_INVALID_VIDEO_PARAM(-15)
3: We try to Close & Init the encoder when the Reset function report error -15, but it's init failed with this error: [ERROR], sts=MFX_ERR_UNSUPPORTED(-3), AllocFrames, Query (for encoder) failed.

This method of changing the resolution is what we have been using in mediasdk and vpl just started.

### What's the usage scenario when you are seeing the problem?

Video Conference, Others

### Do you want to contribute a patch to fix the issue?

Yes, I'm glad to submit a patch to fix it

**Comment by yefeizhou** [comment]
Hello, @DaveHu-TVU which format do you want to encode to? e.g. AVC, AV1, VP9 or others?

**Comment by DaveHu-TVU** [comment]
H.265 1080p
I tested H.264 1080p is works well.

**Comment by yefeizhou** [comment]
> H.265 1080p I tested H.264 1080p is works well.

@thomasli21801 could you please take a look? Thanks

**Comment by DaveHu-TVU** [comment]
Any update for this issue? Thanks.

**Comment by DaveHu-TVU** [comment]
Hi  @thomasli21801 
Any update for this issue? Thanks.
