### ISSUE TITLE
[Bug]: B-Frames + AdaptiveCQM result in bad output

### ISSUE THREAD

**Issue by DatCaptainHorse** [oneapi-src/oneVPL-intel-gpu#295]
### Which component impacted?

Encode

### Is it regression? Good in old configuration?

No, this issue exist a long time

### What happened?

1. In Linux (Ubuntu 23.10 to be specific), compile latest OBS-Studio with VPL Pull Request merged.
2. Select QuickSync H.264 encoder in Recording tab.
3. Turn on B-Frames by raising the value + enable "Subjective video enchantments".
4. Start recording something with heavy movement (e.g. game with lots of screen effects).
5. The output video will be garbled/unplayable at those heavy movement scenes.

GPU: `Intel Arc A380`

Compiled OBS-Studio from commit `e02f782bc62f0497e118316871ba1d15f6b5a6be`

### What's the usage scenario when you are seeing the problem?

Content Creation, Game Streaming

### Debug Information

`intel-media-va-driver-non-free/mantic,now 23.2.3+ds1-1 amd64`
`libigdgmm12/mantic,now 22.3.9+ds1-1 amd64`
```
libva-dev/mantic,now 2.18.0-1 amd64
libva-drm2/mantic,now 2.18.0-1 amd64
libva-glx2/mantic,now 2.18.0-1 amd64
libva-wayland2/mantic,now 2.18.0-1 amd64
libva-x11-2/mantic,now 2.18.0-1 amd64
libva2/mantic,now 2.18.0-1 amd64
```

```
ls /dev/dri
by-path  card0  renderD128
```
[vainfo.log](https://github.com/oneapi-src/oneVPL-intel-gpu/files/12322415/vainfo.log)
[traces.zip](https://github.com/oneapi-src/oneVPL-intel-gpu/files/12322435/traces.zip)

### Do you want to contribute a patch to fix the issue?

None

**Comment by DatCaptainHorse** [comment]
Bad output video in question:
[badOutputVideo.zip](https://github.com/oneapi-src/oneVPL-intel-gpu/files/12322451/badOutputVideo.zip)

Please let me know if source video is needed to help recreate issue.

**Comment by intel-mediadev** [comment]
Auto Created VSMGWL-67521 for further analysis.

**Comment by DatCaptainHorse** [comment]
Closing as this was the fault of the used program due to incorrect oneVPL API usage.
