### ISSUE TITLE
[Bug]: [Regression]Encode av1 cannot output yuv simultaneously  by b89476f8bed87

### ISSUE THREAD

**Issue by wenqingx** [oneapi-src/oneVPL-intel-gpu#298]
### Which component impacted?

Encode

### Is it regression? Good in old configuration?

Yes, it's good in old version

### What happened?

first bad commit: https://github.com/oneapi-src/oneVPL-intel-gpu/commit/b89476f8bed87f6b752f04ac9ded0ef2e38ea463 
libva:4aec726b8b8 
gmmlib: 9032c983b0a8
media-driver:ce81beded8b7
ovpl:ca5bbbb057a6
ffmpeg:fc993e7a53c2

platform:DG2
kernel:6.2.0-23-generic
Os:Ubuntu 20.04.4 LTS

test cmd: (failed)
`ffmpeg -v verbose -init_hw_device qsv=qsv,child_device=/dev/dri/renderD129 -hwaccel_output_format qsv -hwaccel qsv -c:v h264_qsv -i input.264 -an -vsync passthrough -c:v av1_qsv -low_power 1 -vframes 71 -y out.ivf -vf 'hwdownload,format=nv12' -pix_fmt yuv420p -f rawvideo -vframes 71 -y output.yuv`

test cmd(passed)
`ffmpeg -v verbose -init_hw_device qsv=qsv,child_device=/dev/dri/renderD129 -hwaccel_output_format qsv -hwaccel qsv -c:v h264_qsv -i input.264 -an -vsync passthrough -c:v av1_qsv -low_power 1 -vframes 71 -y out.ivf`

### What's the usage scenario when you are seeing the problem?

Others

### Do you want to contribute a patch to fix the issue?

None

**Comment by leyu-yao** [comment]
Hi @wenqingx 
It is reverted now https://github.com/oneapi-src/oneVPL-intel-gpu/commit/c068b82b4fa0769cde89e02a29fa7e700363e425

**Comment by wenqingx** [comment]
> Hi @wenqingx It is reverted now [c068b82](https://github.com/oneapi-src/oneVPL-intel-gpu/commit/c068b82b4fa0769cde89e02a29fa7e700363e425)

thanks , closed
