### ISSUE TITLE
sample_decode not using SFC for color conversion

### ISSUE THREAD

**Issue by gsilva2016** [oneapi-src/oneVPL-intel-gpu#7]
SFC is not used in VEBox nor VDBox on TGL i7 for rgb4 color conversion.

VDBox+SFC
sample_decode h265 -hw -vaapi -i 4k30-Marina6Mbps.hevc -rgb4 -api2x_dispatcher -dec_postproc force
Render usage - 96% 
VEBox - 0%
VDBox - 74%

VEBox+SFC
sample_decode h265 -hw -vaapi -i 4k30-Marina6Mbps.hevc -rgb4 -api2x_dispatcher
Same metrics as above with no change.

libva: 2.11.0
media driver: 21.1.3
onevpl: v2021.2.2
onevpl-gpu: b9619ac842d71240d63e8a0eb210e458d9ff7822

**Comment by dmitryermilov** [comment]
VPL samples are managed in this repo: https://github.com/oneapi-src/oneVPL. Please open there.
