### ISSUE TITLE
sample_decode rendering does not work

### ISSUE THREAD

**Issue by gsilva2016** [oneapi-src/oneVPL-intel-gpu#8]
sample_decode h265 -hw -vaapi -i 4k30-Marina6Mbps.hevc -rgb4 -r

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, m_mfxSession.InitEx failed at pipeline_decode.cpp:429

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, Pipeline.Init failed at sample_decode.cpp:753

libva: 2.11.0
media driver: 21.1.3
onevpl: v2021.2.2
onevpl-gpu: b9619ac842d71240d63e8a0eb210e458d9ff7822

**Comment by dvrogozh** [comment]
This does not seem to be related to rendering since you have failure with session init. Can you, please, provide the following info:
1. What's the HW you use? How many GPUs does it have? Provide full output of `lspci -nn`, please.
2. Provide output from strace, i.e.:
```
strace sample_decode h265 -hw -vaapi -i 4k30-Marina6Mbps.hevc -rgb4 -r
```

**Comment by dmitryermilov** [comment]
@gsilva2016 , any reply?
